# Generated by Django 3.2.3 on 2021-05-28 18:54

from django.db import migrations, models
import django.db.models.deletion
import projectapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('adrs', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Total_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_round', models.IntegerField(blank=True)),
                ('second_round', models.IntegerField(blank=True)),
                ('third_round', models.IntegerField(blank=True)),
                ('calc_score', models.PositiveIntegerField(verbose_name=projectapp.models.Total_score.total_score)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.candidate')),
            ],
        ),
    ]
