# Generated by Django 3.2.3 on 2021-05-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_rename_adrs_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
