# Generated by Django 3.2.3 on 2021-05-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='ccc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
