# Generated by Django 3.2.3 on 2021-05-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_auto_20210529_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ccc',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectapp.user')),
            ],
        ),
    ]
